name: CustomJoinMessage
version: '${version}'
main: org.dark.customjoinmessage.CustomJoinMessage
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  cjm:
    description: Allow players to set a custom join and quit message.
    usage: /<command> [reload|setjoinmessage|setquitmessage]
    aliases: [customjoinmessage]