name: CustomJoinMessage
version: '1.0.5'
main: org.dark.customjoinmessage.CustomJoinMessage
api-version: '1.20'
softdepend:
  - PlaceholderAPI
commands:
  cjm:
    description: Allow players to set a custom join and quit message.
    usage: /<command> [reload|setjoinmessage|setquitmessage]
    aliases: [customjoinmessage]