name: CustomJoinMessage
version: '1.0.6'
main: org.dark.customjoinmessage.CustomJoinMessage
api-version: '1.20'
softdepend:
  - PlaceholderAPI
commands:
  cjm:
    description: Allow players to set a custom join and quit message.
    usage: /<command> [gui|setjoinmessage|setquitmessage]
    aliases: [customjoinmessage]
  acjm:
    description: Admin commands for cjm.
    usage: /acjm (reload/showjoinmessage/showquitmessage/setjoinmessage/setquitmessage/deljoinmessage) (nickname)