name: CustomJoinMessage
version: '${version}'
main: org.dark.customjoinmessage.CustomJoinMessage
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  cjm:
    description: Main command for CustomJoinMessage plugin
    usage: /<command> [reload|setjoinmessage|setquitmessage]
    aliases: [customjoinmessage]